#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2014 uralbash <root@uralbash.ru>
#
# Distributed under terms of the MIT license.

sudo: false
language: python

notifications:
  email: "sacrud@uralbash.ru"
  irc:
    channels:
      - "chat.freenode.net#sacrud"
    on_success: change
    on_failure: always

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

script:
  - python setup.py test

after_success:
  - pip install coveralls
  - coveralls
